routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\SellerController;
use App\Http\Controllers\PesananController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CustomerController;

Auth::routes();

Route::get('/',[CustomerController::class,'index']);
Route::get('/tentang-kami',[CustomerController::class,'tentangkami']);

Route::middleware(['auth'])->group(function(){
    //CART
    Route::get('/cart',[CartController::class,'index']);
    Route::get('/checkout', [CartController::class, 'checkout'])->name('checkout');
    Route::get('/pesanan', [CartController::class, 'pesanan'])->name('pesanan');
    Route::get('/checkout/success/{no_pesanan}', [CartController::class, 'success'])->name('checkout-success');
    Route::get('/checkout/cancel/{no_pesanan}', [CartController::class, 'cancelOrder'])->name('cancel-order');
    Route::get('/pesanan/{details}', [CartController::class, 'detailPesanan'])->name('pesanan.show.details');
    Route::post('/add-to-cart', [CartController::class, 'addToCart'])->name('add-to-cart');
    Route::get('/remove-from-cart/{id}', [CartController::class, 'removeFromCart'])->name('remove-from-cart');
    Route::post('/update-cart/{id}', [CartController::class, 'updateCart'])->name('update-cart');
    // Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout');
    Route::delete('/orders/{no_pesanan}', [CartController::class, 'deleteOrder']);
    Route::get('/pesanan/{no_pesanan}/proses', [CartController::class, 'finishOrder'])->name('finish.order');
    Route::post('/pesanan/{produk}/review', [ReviewController::class, 'store'])->name('produk.review.store');
    Route::put('/pesanan/{review}/review', [ReviewController::class, 'update'])->name('produk.review.update');
    Route::get('daftartoko', [SellerController::class, 'createtoko']);
    Route::post('daftartoko', [SellerController::class, 'storetoko']);
    Route::get('/admin',[AdminController::class,'index']); 
});

Route::prefix('akun')->middleware(['auth'])->group(function(){
    Route::get('/', [ProfileController::class, 'index'])->name('profile.view');
    Route::put('/update-photo/{profile_id}', [ProfileController::class, 'updatePhoto'])->name('profile.photo.update');
    Route::get('/alamat', [ProfileController::class, 'showAlamat'])->name('profile.alamat.show');
    Route::post('/alamat', [ProfileController::class, 'storeAlamat'])->name('profile.alamat.save');
    Route::get('/alamat/ubah/{id}', [ProfileController::class, 'editAlamat'])->name('profile.alamat.edit');
    Route::put('/alamat/ubah/{id}', [ProfileController::class, 'updateAlamat'])->name('profile.alamat.update');
});

Route::prefix('menu')->group(function(){
    Route::get('/', [CustomerController::class, 'showMenu'])->name('produks.show');
    Route::get('/search', [CustomerController::class, 'search'])->name('produks.search');
    Route::get('/{produk_slug}/details', [CustomerController::class, 'showProdukDetail']);
    Route::get('/{kategorislug}', [CustomerController::class, 'showKategori']);
    Route::get('/{kategorislug}/q', [CustomerController::class, 'sortBy'])->name('produks.sortby');
    Route::get('/{kategorislug}/{produk_slug}', [CustomerController::class, 'showKategoriProduk']);
});

Route::prefix('toko')->middleware(['auth', 'seller'])->group(function(){
    Route::get('/', [SellerController::class, 'index'])->name('dashboard');
    Route::get('/pengaturan', [SellerController::class, 'editToko'])->name('edit-toko');
    Route::put('/pengaturan/{toko_id}', [SellerController::class, 'updateToko'])->name('update-toko');
    Route::put('/update-photo/{toko_id}', [SellerController::class, 'updatePhoto'])->name('profile.photo.toko.update');
    
    Route::get('produk', [ProdukController::class, 'index']);
    Route::get('produk/tambah', [ProdukController::class, 'create']);
    Route::post('produk/tambah', [ProdukController::class, 'store']);
    Route::get('produk/edit/{produk_id}', [ProdukController::class, 'edit']);
    Route::put('produk/edit/{produk_id}', [ProdukController::class, 'update']);
    Route::get('produk/hapus/{produk_id}', [ProdukController::class, 'destroy'])->name('produk.destroy');
    Route::delete('/delete-image/{id}', [ProdukController::class, 'deleteImage'])->name('delete.image');
    
    Route::get('pesanan', [PesananController::class, 'index'])->name('pesanan');
    Route::get('pesanan/{no_pesanan}', [PesananController::class, 'detailPesanan'])->name('detail-pesanan');
    Route::get('pesanan/proses/{no_pesanan}', [PesananController::class, 'prosesPesanan'])->name('proses-pesanan');
    
    Route::get('saldo', [SellerController::class, 'showSaldo'])->name('show.saldo');
    Route::put('/saldo/{toko_id}', [SellerController::class, 'updateNomorRekening'])->name('update.no.rekening');
    Route::post('/saldo/{toko_id}', [SellerController::class, 'catatPenarikan'])->name('simpan.nominal');
});

Route::prefix('admin')->middleware(['auth', 'admin'])->group(function(){
    Route::get('/', [AdminController::class, 'index'])->name('dashboard.admin');
    Route::get('toko', [AdminController::class, 'showToko'])->name('show.toko');
    Route::get('saldo', [AdminController::class, 'showRequest'])->name('show.saldo');
    Route::get('saldo/terima/{saldo}', [AdminController::class, 'acceptRequest'])->name('accept.request');
});

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    use HasFactory;

    protected $table = 'produks';

    protected $fillable = [
        'kategori_id',
        'user_id',
        'nama',
        'slug',
        'harga_list',
        'harga_netto',
        'stok',
        'deskripsi',
    ];

    public function kategori(){
        return $this->belongsTo(Kategori::class, 'kategori_id', 'id');
    }
    public function images(){
        return $this->hasMany(ProdukImage::class);
    }
    public function toko()
    {
        return $this->belongsTo(Toko::class, 'user_id', 'user_id');
    }
    public function cart(){
        return $this->hasMany(Cart::class);
    }
    public function orders(){
        return $this->hasMany(Order::class);
    }
    public function getAcceptedOrdersCountAttribute()
    {
        return $this->orders()->where('status', 'Diterima')->count();
    }
    public function reviews() {
        return $this->hasMany(Review::class);
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Models\ProdukImage;
use App\Models\toko;
use App\Models\User;
use App\Models\Produk;
use App\Models\Kategori;
use App\Models\Review;
use Illuminate\Http\Request;
use Carbon\Carbon;



class CustomerController extends Controller
{
    public function index(Request $request)
    {
        $kategori = Kategori::all();
        $produks = Produk::with('kategori', 'reviews')->paginate(8);
        // dd($produks->first());
        return view('customer.index', compact('produks', 'kategori'));
    }
    public function loadMore(Request $request)
    {
        $skip = $request->skip;
        $take = 12; // Jumlah produk yang akan dimuat setiap kali "Load More" diklik

        $produks = Produk::with('images', 'kategori', 'reviews')->skip($skip)->take($take)->get();
        return response()->json($produks);
    }
    public function search(Request $request)
    {
        $query = Produk::query();

        if ($request->has('q') && $request->q) {
            $query->where('nama', 'like', '%' . $request->q . '%');
        }

        if ($request->has('min_price') && $request->min_price) {
            $query->where('harga_netto', '>=', $request->min_price);
        }

        if ($request->has('max_price') && $request->max_price) {
            $query->where('harga_netto', '<=', $request->max_price);
        }
        
        if ($request->has('sort_by') && $request->sort_by) {
            if ($request->sort_by == 'harga_terendah') {
                $query->orderBy('harga_netto', 'asc');
            } elseif ($request->sort_by == 'harga_tertinggi') {
                $query->orderBy('harga_netto', 'desc');
            } elseif ($request->sort_by == 'terbaru') {
                $query->orderBy('created_at', 'desc');
            }
        }

        $produks = $query->paginate(5);
        $kategori = Kategori::all();
        return view('customer.menu.index', compact('produks', 'kategori'));
    }
    public function showMenu()
    {
        $kategori = Kategori::all();
        $produks = Produk::with('kategori')->with('images')->paginate(5);
        return view('customer.menu.index', compact('produks', 'kategori'));
    }

    public function showKategori($slug)
    {
        $kategoris = Kategori::all();
        $kategori = Kategori::where('slug', '=', $slug)->first();

        // dd($slug);
        if($kategori){
            $produks = Produk::where('kategori_id', '=', $kategori->id)->with('kategori')->with('images')->paginate(5);
        }else{
            $produks = Produk::with('kategori')->with('images')->paginate(5);
        }
        $imageProduk = Produk::with('images')->get();
        return view('customer.menu.produk', compact('produks', 'kategoris', 'kategori', 'imageProduk'));
    }

    public function sortBy(Request $request, $slug){
        $kategoris = Kategori::all();
        $kategori = Kategori::where('slug', '=', $slug)->first();
        $query = Produk::query();
        if ($request->has('min_price') && $request->min_price) {
            $query->where('kategori_id', $kategori->id)->where('harga_netto', '>=', $request->min_price);
        }

        if ($request->has('max_price') && $request->max_price) {
            $query->where('kategori_id', $kategori->id)->where('harga_netto', '<=', $request->max_price);
        }

        if ($request->has('sort_by') && $request->sort_by) {
            if ($request->sort_by == 'harga_terendah') {
                $query->where('kategori_id', $kategori->id)->orderBy('harga_netto', 'asc');
            } elseif ($request->sort_by == 'harga_tertinggi') {
                $query->where('kategori_id', $kategori->id)->orderBy('harga_netto', 'desc');
            } elseif ($request->sort_by == 'terbaru') {
                $query->where('kategori_id', $kategori->id)->orderBy('created_at', 'desc');
            }
        }

        $produks = $query->paginate(5);
        return view('customer.menu.produk', compact('produks', 'kategoris', 'kategori'));
    }
    public function showKategoriProduk($slug)
    {
        $kategoris = Kategori::all();
        $kategori = Kategori::where('slug', '=', $slug)->first();

        // dd($slug);
        if($kategori){
            $produks = Produk::where('kategori_id', '=', $kategori->id)->with('kategori')->with('images')->get();
        }else{
            $produks = Produk::with('kategori')->with('images')->get();
        }
        return view('customer.menu.produk', compact('produks', 'kategoris', 'kategori'));
    }

    function showProdukDetail($slug)
    {
        $produk = Produk::with('kategori', 'images')->where('slug', $slug)->first();
        //dd($produk);
        $kategori = Kategori::all();
        //dd($produks);
        $toko = Toko::where('user_id', $produk->user_id)->first();
        $imageProduk = Produk::with('images')->get();
        //dd($toko);
        //dd($imageProduk);
        $reviews = Review::where('produk_id', $produk->id)->get();
        // dd($reviews);
        return view('customer.produk', compact('produk', 'imageProduk', 'kategori', 'toko'));
    }

    function tentangkami()
    {
        return view('customer.tentangkami');
    }
}

resources/views/customer/menu/index.blade.php
@extends('layouts.user.main')
@section('content')
<main class="main">
    <div class="page-header text-center" style="background-image: url({{ asset('img/banner-title.jpg') }})">
        <div class="container">
            <h1 class="page-title">Produk<span>Shop</span></h1>
        </div><!-- End .container -->
    </div><!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav mb-2">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url('/home') }}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Produk</li>
            </ol>
        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->
    @if(session('swal_success'))
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                Swal.fire({
                    icon: 'success',
                    title: 'Success!',
                    text: '{{ session('swal_success') }}',
                });
            });
        </script>
    @endif
    <div class="page-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="toolbox">
                        {{-- <div class="toolbox-left">
                            <div class="toolbox-info">
                                Menampilkan <span>{{ $produks->perPage() }} dari {{ $produks->total() }}</span> Produk
                            </div><!-- End .toolbox-info -->
                        </div> --}}
                        <div class="toolbox-right">
                            <div class="toolbox-sort">
                                <label for="sort_by">Urutkan :</label>
                                <form method="GET" action="{{ route('produks.search') }}" id="searchForm">
                                    <div class="select-custom">
                                        <select name="sort_by" id="sort_by" class="form-control">
                                            <option value="" disabled selected>Pilih Urutan</option>
                                            <option value="harga_terendah" {{ request()->sort_by == 'harga_terendah' ? 'selected' : '' }}>Harga Terendah</option>
                                            <option value="harga_tertinggi" {{ request()->sort_by == 'harga_tertinggi' ? 'selected' : '' }}>Harga Tertinggi</option>
                                            <option value="terbaru" {{ request()->sort_by == 'terbaru' ? 'selected' : '' }}>Terbaru</option>
                                        </select>
                                    </div>
                                    <button type="submit" class="btn btn-primary" hidden>Search</button>
                                </form>
                            </div><!-- End .toolbox-sort -->
                        </div><!-- End .toolbox-right -->
                    </div><!-- End .toolbox -->

                    <div class="products mb-3">
                        @foreach ($produks as $produk)
                        <div class="product product-list">
                            <div class="row">
                                <div class="col-6 col-lg-3">
                                    <figure class="product-media">
                                            <a href="{{ url('menu/'.$produk->slug.'/details') }}">
                                                @if ($produk->images->isEmpty())
                                                    <img src="{{ asset('img/default.jpg') }}" alt="Product image" class="product-image">    
                                                @else
                                                    <img src="{{ asset($produk->images->first()->images) }}" alt="Product image" class="product-image">    
                                                @endif
                                            </a>
                                    </figure><!-- End .product-media -->
                                </div><!-- End .col-sm-6 col-lg-3 -->

                                <div class="col-6 col-lg-4 order-lg-last">
                                    <div class="product-list-action">
                                        <div class="product-price m-0" >
                                            Rp. {{ number_format($produk->harga_netto, 0, ',', '.') }}
                                        </div><!-- End .product-price -->
                                        <div class="product-content mb-1">
                                            {{ $produk->accepted_orders_count }} Terjual
                                        </div>
                                        @if ($produk->reviews->isNotEmpty())
                                        @foreach($produk->reviews as $review)
                                            <div class="ratings-container">
                                                <div class="ratings">
                                                    <div class="ratings-val" style="width: {{ ($review->rating / 5) * 100 }}%;"></div><!-- End .ratings-val -->
                                                </div><!-- End .ratings -->
                                                <span class="ratings-text">({{ $review->rating }} / 5)</span>
                                            </div><!-- End .ratings-container -->
                                        @endforeach
                                        @else     
                                        <div class="ratings-container">
                                            <div class="ratings">
                                                <div class="ratings-val" style="width: 0%;"></div><!-- End .ratings-val -->
                                            </div><!-- End .ratings -->
                                            <span class="ratings-text">( 0 / 5 )</span>
                                        </div><!-- End .rating-container -->
                                        @endif
                                        <div>
                                            <a href="#" class="btn btn-primary btn-rounded mb-2" onclick="event.preventDefault(); document.getElementById('add-to-cart-form-{{ $produk->id }}').submit();">
                                                <i class="fa-solid fa-cart-plus"></i>
                                                <span>Tambah Ke Keranjang</span>
                                            </a>
                                        </div>
                                        <form id="add-to-cart-form-{{ $produk->id }}" action="{{ route('add-to-cart') }}" method="POST" style="display: none;">
                                            @csrf
                                            <input type="hidden" name="produk_id" value="{{ $produk->id }}">
                                            <input type="hidden" name="qty" value="1">
                                        </form>
                                    </div><!-- End .product-list-action -->
                                </div><!-- End .col-sm-6 col-lg-3 -->

                                <div class="col-lg-5">
                                    <div class="product-body product-action-inner">
                                        <div class="product-cat">
                                            <a>{{ $produk->kategori->nama }}</a>
                                        </div><!-- End .product-cat -->
                                        <h3 class="product-title">
                                            <a href="{{ url('menu/'.$produk->slug.'/details') }}">{{ $produk->nama }}</a>
                                        </h3>

                                        <div class="product-content">
                                            <p>{{ $produk->deskripsi}} </p>
                                        </div><!-- End .product-content -->

                                        <div class="product-nav product-nav-thumbs">
                                            @foreach ($produk->images as $item)    
                                                    <a href="#" class="active">
                                                        <img src="{{ asset($item->images) }}"alt="product desc">
                                                    </a>
                                            @endforeach
                                        </div><!-- End .product-nav -->
                                    </div><!-- End .product-body -->
                                </div><!-- End .col-lg-6 -->
                            </div><!-- End .row -->
                        </div><!-- End .product -->
                        @endforeach
                    </div><!-- End .products -->
                    <div class="d-flex justify-content-center">
                        {{ $produks->links('vendor.pagination.custom-pagination') }}
                    </div>
                </div><!-- End .col-lg-9 -->
                <aside class="col-lg-3 order-lg-first">
                    <div class="sidebar sidebar-shop">
                        <div class="widget widget-collapsible">
                            <h3 class="widget-title">
                                <a data-toggle="collapse" href="#widget-1" role="button" aria-expanded="true"
                                    aria-controls="widget-1">
                                    Category
                                </a>
                            </h3><!-- End .widget-title -->

                            <div class="collapse show" id="widget-1">
                                <div class="widget-body">
                                    <div class="filter-items">
                                        <div class="filter-item">
                                            @foreach ($kategori as $item)
                                            <div class="mx-3">
                                                <a href="{{ url('/menu/'.$item->slug ) }}">{{ $item->nama }}</a>
                                            </div><!-- End .custom-checkbox -->
                                            @endforeach
                                        </div><!-- End .filter-item -->
                                    </div><!-- End .filter-items -->
                                </div><!-- End .widget-body -->
                            </div><!-- End .collapse -->
                        </div><!-- End .widget -->
                        <div class="widget widget-collapsible">
                            <h3 class="widget-title">
                                <a data-toggle="collapse" href="#widget-5" role="button" aria-expanded="true"
                                    aria-controls="widget-5">
                                    Price
                                </a>
                            </h3><!-- End .widget-title -->

                            <div class="collapse show" id="widget-5">
                                <div class="widget-body">
                                    <div class="filter-price">
                                        <form method="GET" action="{{ route('produks.search') }}">
                                            <div class="form-group">
                                                <label for="min_price">Min Harga</label>
                                                <input type="number" class="form-control" id="min_price" name="min_price" value="{{ request()->min_price }}">
                                            </div>
                                            <div class="form-group">
                                                <label for="max_price">Max Harga</label>
                                                <input type="number" class="form-control" id="max_price" name="max_price" value="{{ request()->max_price }}">
                                            </div>
                                            <button type="submit" class="btn btn-primary">Cari</button>
                                        </form>
                                    </div><!-- End .filter-price -->
                                </div><!-- End .widget-body -->
                            </div><!-- End .collapse -->
                        </div><!-- End .widget -->
                    </div><!-- End .sidebar sidebar-shop -->
                </aside><!-- End .col-lg-3 -->
            </div><!-- End .row -->
        </div><!-- End .container -->
    </div><!-- End .page-content -->
</main><!-- End .main -->
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        const orderBy = document.getElementById('sort_by');
        orderBy.addEventListener('change', () => {
            const form = document.getElementById('searchForm');
            form.submit();
        });
    });
</script>
@endsection